/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Checks NOTHING and returns 200 unconditionally.
         *
         *     That is the correct implementation, not laziness. Failing liveness makes the kubelet KILL
         *     the container, so the only question it should answer is "is this process so broken that a
         *     restart is the remedy?" A restart fixes a deadlock; it does not fix an unreachable database,
         *     and trying makes a brief dependency blip into a cluster-wide restart storm.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The process is alive. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @constant */
                            status?: "ok";
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Reports whether this replica can serve traffic, with per-dependency detail.
         *
         *     Failing removes the pod from Service endpoints WITHOUT restarting it, so traffic drains and
         *     returns automatically once the dependency recovers.
         *
         *     Returns 503, not 500: the service is working correctly and temporarily cannot serve.
         *
         *     **Must not be exposed through a public ingress** -- the response includes dependency error
         *     strings, which can name internal hosts.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Every dependency is usable. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthReport"];
                    };
                };
                /** @description At least one dependency is unusable. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthReport"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Which build is running
         * @description **Requires authentication**, unlike the probes. An audit found this documented as `security: []`
         *     while the server returned 401 for it -- the spec was wrong, not the code.
         *
         *     The probe exemption exists because the kubelet cannot present a credential and a 401 on a probe
         *     kills the container. Nothing probes `/version`, so it gains nothing from being open, and build
         *     version and commit are precisely what an attacker fingerprints to find known CVEs in a
         *     dependency tree.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Build metadata injected at link time. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 2ff2824 */
                            version?: string;
                            /** @example 2ff2824 */
                            commit?: string;
                            /** Format: date-time */
                            build_time?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/costs/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Aggregated cost over a time range
         * @description The primary reporting endpoint. Aggregates cost across a half-open range `[from, to)`,
         *     grouped by one dimension.
         *
         *     `totals` is summed from the rows actually returned, so the headline figure can never
         *     disagree with the rows beneath it. When `totals.truncated` is true the row set was cut short
         *     by `limit` and the totals cover only what was returned.
         */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description Start of the range, inclusive. RFC3339 **with a timezone**.
                     *
                     *     One format only, deliberately: `01/02/2026` is January 2nd or February 1st depending on
                     *     where the caller lives, and guessing wrong shifts a whole cost report by a month.
                     *
                     *     Defaults to 24 hours before `to`.
                     */
                    from?: components["parameters"]["From"];
                    /**
                     * @description End of the range, **exclusive**. The range is half-open `[from, to)`, matching the collection
                     *     windows -- a closed range would double-count the boundary window in two adjacent reports.
                     *
                     *     Defaults to now. The range may span at most 400 days.
                     */
                    to?: components["parameters"]["To"];
                    /** @description The dimension to aggregate by. */
                    group_by?: "capacity_type" | "container" | "cost_centre" | "environment" | "instance_type" | "namespace" | "node" | "pod" | "team" | "workload";
                    /** @description Which value to order by. */
                    sort?: "cpu_cost" | "cpu_core_hours" | "dimension" | "memory_cost" | "total_cost" | "wasted_cpu_core_hours";
                    order?: "asc" | "desc";
                    /**
                     * @description Maximum rows. **Refused, not clamped**, if too large: silently returning 100 rows to a
                     *     caller who asked for 10,000 would make them believe they had the whole result set.
                     */
                    limit?: number;
                    namespace?: components["parameters"]["Namespace"];
                    team?: components["parameters"]["Team"];
                    environment?: components["parameters"]["Environment"];
                    cost_centre?: components["parameters"]["CostCentre"];
                    workload_kind?: components["parameters"]["WorkloadKind"];
                    workload_name?: components["parameters"]["WorkloadName"];
                    node?: components["parameters"]["Node"];
                    instance_type?: components["parameters"]["InstanceType"];
                    capacity_type?: components["parameters"]["CapacityType"];
                    /** @description Return only rows priced from a fallback rate, to answer "how much of this bill is guessed?" */
                    estimated_only?: components["parameters"]["EstimatedOnly"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The aggregated cost. */
                200: {
                    headers: {
                        /**
                         * @description `private, max-age=60`. Private rather than public: these responses are scoped to
                         *     whoever authenticated, and a shared proxy caching one caller's report and serving it
                         *     to another would be a data leak.
                         */
                        "Cache-Control"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CostSummaryResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["RateLimited"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/allocations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Raw per-container cost samples, cursor-paginated
         * @description The rows a summary was computed from. Use this when a figure looks wrong: it returns
         *     requested, used AND billable separately, so the `max(requested, used)` rule is visible
         *     rather than implied.
         *
         *     **Cursor pagination, not offset.** Offset would make Postgres scan and discard N rows, and
         *     it is inconsistent under concurrent writes -- the collector appends every five minutes, so
         *     rows shift between requests and a client silently sees a duplicate or misses one. A cursor
         *     asks for "rows after this exact position", which is an index range scan and stable.
         *
         *     The cursor is **opaque**. Do not parse it: its internal shape may change, and a client that
         *     depends on it has coupled itself to our primary key. Follow `next_cursor` until it is absent.
         */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description Start of the range, inclusive. RFC3339 **with a timezone**.
                     *
                     *     One format only, deliberately: `01/02/2026` is January 2nd or February 1st depending on
                     *     where the caller lives, and guessing wrong shifts a whole cost report by a month.
                     *
                     *     Defaults to 24 hours before `to`.
                     */
                    from?: components["parameters"]["From"];
                    /**
                     * @description End of the range, **exclusive**. The range is half-open `[from, to)`, matching the collection
                     *     windows -- a closed range would double-count the boundary window in two adjacent reports.
                     *
                     *     Defaults to now. The range may span at most 400 days.
                     */
                    to?: components["parameters"]["To"];
                    /** @description Opaque position from a previous response's `next_cursor`. Omit for the first page. */
                    cursor?: string;
                    limit?: number;
                    namespace?: components["parameters"]["Namespace"];
                    team?: components["parameters"]["Team"];
                    environment?: components["parameters"]["Environment"];
                    cost_centre?: components["parameters"]["CostCentre"];
                    workload_kind?: components["parameters"]["WorkloadKind"];
                    workload_name?: components["parameters"]["WorkloadName"];
                    node?: components["parameters"]["Node"];
                    instance_type?: components["parameters"]["InstanceType"];
                    capacity_type?: components["parameters"]["CapacityType"];
                    /** @description Return only rows priced from a fallback rate, to answer "how much of this bill is guessed?" */
                    estimated_only?: components["parameters"]["EstimatedOnly"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description One page of allocations. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AllocationsResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["RateLimited"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What to change, and what it would save
         * @description Turns observed behaviour into actionable advice. Five rules: right-size, idle, under-requested,
         *     set-requests and over-replicated.
         *
         *     **`estimated_monthly_saving` can be NEGATIVE.** An under-requested container needs a LARGER
         *     request, which costs more. A tool whose advice is all one-directional is not trusted with
         *     production, so the increase is reported honestly -- and `totals` separates savings from
         *     required increases rather than netting them, so a large saving cannot hide a reliability fix.
         *
         *     **Severity is not ordered by money.** A memory under-request risking an OOM kill is `critical`
         *     even though acting on it costs money; a large saving on a batch job is merely `info`.
         *
         *     **Silence is a valid answer.** Every rule refuses to fire without enough evidence -- a minimum
         *     window count, a minimum observation span, and trustworthy peak data. Recommending a deletion
         *     from twenty minutes of data collected overnight would be worse than saying nothing.
         *
         *     The default range is **7 days**, wider than the cost endpoints' 24 hours: a recommendation from
         *     one day cannot see a weekly pattern, so a job that runs on Sundays would look abandoned.
         */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description Start of the range, inclusive. RFC3339 **with a timezone**.
                     *
                     *     One format only, deliberately: `01/02/2026` is January 2nd or February 1st depending on
                     *     where the caller lives, and guessing wrong shifts a whole cost report by a month.
                     *
                     *     Defaults to 24 hours before `to`.
                     */
                    from?: components["parameters"]["From"];
                    /**
                     * @description End of the range, **exclusive**. The range is half-open `[from, to)`, matching the collection
                     *     windows -- a closed range would double-count the boundary window in two adjacent reports.
                     *
                     *     Defaults to now. The range may span at most 400 days.
                     */
                    to?: components["parameters"]["To"];
                    limit?: number;
                    namespace?: components["parameters"]["Namespace"];
                    team?: components["parameters"]["Team"];
                    environment?: components["parameters"]["Environment"];
                    cost_centre?: components["parameters"]["CostCentre"];
                    workload_kind?: components["parameters"]["WorkloadKind"];
                    workload_name?: components["parameters"]["WorkloadName"];
                    node?: components["parameters"]["Node"];
                    instance_type?: components["parameters"]["InstanceType"];
                    capacity_type?: components["parameters"]["CapacityType"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The recommendations, most urgent first. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecommendationsResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["RateLimited"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/costs/trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cost through time, from the daily rollup
         * @description The same question `/costs/summary` answers for one period, asked repeatedly.
         *
         *     **Which table answers this is reported in `source`, and it is part of the contract.** The daily
         *     rollup is roughly 293x smaller than the fact table (measured), but it cannot answer every
         *     question, so the query is routed:
         *
         *     | Request | Source | Why |
         *     |---|---|---|
         *     | `interval=day\|week\|month` | `daily_rollup` | the rollup's grain is a day, so these aggregate from it exactly |
         *     | `interval=hour` | `raw_facts` | there is no hourly data in the rollup to read |
         *     | `group_by=pod\|container` | `raw_facts` | pod is the one groupable dimension the rollup drops |
         *
         *     The two sources agree for any question both can serve — there is a test asserting exactly that —
         *     but they differ in what they *can* serve, and the rollup only covers days the rollup job has
         *     processed. So a rollup-sourced series can legitimately stop short of today, and a client
         *     comparing this against `/costs/summary` needs to know which it got.
         *
         *     **`window_count` on every point is not decoration.** A bucket with a tenth of its neighbours'
         *     window count is a collection gap, not a cost saving, and on a chart those look identical.
         */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description Bucket width. `hour` is limited to 14 days: it reads the fact table, and 336 points is
                     *     already the practical ceiling for a line chart.
                     */
                    interval?: "hour" | "day" | "week" | "month";
                    /**
                     * @description Inclusive lower bound, RFC3339. Defaults to 30 days ago — wider than the cost endpoints'
                     *     24 hours and the recommendation endpoint's 7 days, because a trend with two points is not
                     *     a trend.
                     */
                    from?: string;
                    /** @description Exclusive upper bound, RFC3339. Defaults to now. */
                    to?: string;
                    /** @description One series per distinct value of this dimension. */
                    group_by?: "namespace" | "team" | "environment" | "cost_centre" | "workload" | "node" | "instance_type" | "capacity_type" | "pod" | "container";
                    /**
                     * @description `previous_period` adds a comparison against the immediately preceding window of EQUAL
                     *     length — not the previous calendar month, which is ambiguous for a 10-day range and makes
                     *     a 31-day month look 3% dearer than a 30-day one.
                     */
                    compare?: "previous_period" | "none";
                    /**
                     * @description Caps SERIES, not points. A truncated series would draw a chart that stops partway through
                     *     the range with nothing to say why.
                     */
                    limit?: number;
                    namespace?: components["parameters"]["Namespace"];
                    team?: components["parameters"]["Team"];
                    environment?: components["parameters"]["Environment"];
                    cost_centre?: components["parameters"]["CostCentre"];
                    workload_kind?: components["parameters"]["WorkloadKind"];
                    workload_name?: components["parameters"]["WorkloadName"];
                    node?: components["parameters"]["Node"];
                    instance_type?: components["parameters"]["InstanceType"];
                    capacity_type?: components["parameters"]["CapacityType"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description One series per group, each ordered oldest bucket first. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TrendResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["RateLimited"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/monthly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Monthly statements, frozen once signed off
         * @description Not "what is true now" — **what we said**. Every other endpoint here is a view of current data.
         *     This one is stored, because a statement must not change after it is issued: backfill a missing
         *     day, correct a price, or fix a rollup bug, and a computed-on-demand figure for last August
         *     silently becomes a different number from the one somebody already reported.
         *
         *     `finalised_at` is the line. `null` means provisional and regenerable; set means frozen — and
         *     frozen is enforced by database triggers, not only by the writer that happens to set it.
         *
         *     **Read `coverage` before quoting any total.** A month containing a collector outage produces a
         *     figure that is confidently too low, and nothing about the figure itself reveals that. Coverage is
         *     `days_with_data / days_in_month`, so it is DAY-level: a day on which the collector ran for one
         *     hour counts as a full day. `window_count` is reported alongside for exactly that reason, and the
         *     daily trend is where a partial day is visible as a dip.
         *
         *     Statements exist at three scopes. The gap between a cluster statement and the sum of its team
         *     statements IS the unattributed spend — cost whose containers carry no team label, which gets no
         *     team statement rather than one belonging to nobody.
         */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description First month, as `YYYY-MM`. Defaults to 11 months ago. A timestamp is REFUSED rather than
                     *     truncated to its month, because silently discarding the day answers a different question.
                     */
                    from?: string;
                    /**
                     * @description Last month, `YYYY-MM`, **INCLUSIVE** — the one place this API is not half-open, and
                     *     deliberately. A month is a label, not an instant, and "January to March" means three months
                     *     to everyone who asks for it.
                     */
                    to?: string;
                    /** @description Omit to return all three scopes. */
                    scope_kind?: "cluster" | "namespace" | "team";
                    /** @description The namespace, team or cluster name to filter to. */
                    scope_value?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Statements, newest month first, largest cost first within a month. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MonthlyReportsResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["RateLimited"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cluster nodes with their rates
         * @description Live node topology from the informer cache, with the per-resource rates the pricing engine
         *     derives for each.
         *
         *     A node that cannot be priced is **still returned**, carrying `pricing.error`. Failing the
         *     whole request because one node in fifty has an unrecognised instance type would make the
         *     endpoint useless; omitting it silently would hide capacity that exists and costs money.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Every node, up to the response limit. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InventoryList"] & {
                            items?: components["schemas"]["Node"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["RateLimited"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/namespaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Namespaces and their cost-allocation dimensions */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Every namespace, up to the response limit. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InventoryList"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["RateLimited"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pods with requests, QoS class and resolved workload */
        get: {
            parameters: {
                query?: {
                    /** @description Restrict to one namespace. Must be a DNS-1123 label. */
                    namespace?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Matching pods, up to the response limit. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InventoryList"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["RateLimited"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description The envelope every inventory endpoint returns. One component rather than three inline copies:
         *     the three were duplicated, and an audit found they had already drifted -- two of them omitted
         *     the truncation fields and two omitted their 429 and 500 responses.
         */
        InventoryList: {
            items: Record<string, never>[];
            /** @description Items in THIS response. Equals `total` unless the response was truncated. */
            count: number;
            /**
             * @description How many items existed BEFORE the limit was applied. Read this against `count`: a caller
             *     given 500 of 5,000 and not told would treat the 500 as the whole cluster.
             */
            total: number;
            /**
             * @description Present and true only when the response is incomplete. These endpoints were unbounded until
             *     a Phase 7 audit: at a measured 950 bytes per pod, and with the response buffered before
             *     writing, a 5,000-pod cluster meant 4.5 MiB allocated per request.
             *
             *     Truncation keeps the first N of a stable order -- the informer's listers sort -- so two
             *     identical requests agree rather than returning different subsets.
             */
            truncated?: boolean;
        };
        /**
         * @description An exact decimal as a STRING. A JSON number would be parsed as a double by every JavaScript
         *     client and lose precision. Format for display; do not compute with it.
         * @example 0.0185500000
         */
        Money: string;
        CostSummaryResponse: {
            /**
             * Format: date-time
             * @description Echoed back, because a caller who omitted it received a default it never chose.
             */
            from: string;
            /** Format: date-time */
            to: string;
            group_by: string;
            count: number;
            items: components["schemas"]["CostSummaryRow"][];
            /**
             * @description The aggregate across every RETURNED row, computed server-side.
             *
             *     **A client must not sum the rows itself**, for two independent reasons. These are exact
             *     decimals of up to 26 significant digits, so adding them in JavaScript means `parseFloat`
             *     and a silent truncation to a double that compounds across rows — the whole reason money
             *     crosses the wire as a string. And when `truncated` is true the returned rows are not the
             *     complete answer, so no amount of client-side care can produce the real figure.
             */
            totals: {
                total_cost: components["schemas"]["Money"];
                cpu_cost: components["schemas"]["Money"];
                memory_cost: components["schemas"]["Money"];
                cpu_billable_core_hours: components["schemas"]["Money"];
                memory_billable_gib_hours: components["schemas"]["Money"];
                /**
                 * @description The headline figure this API exists to report. Summed from per-row values that were each
                 *     floored in SQL — never computed as a difference of totals, which would let an
                 *     under-requested group credit against a wasteful one.
                 */
                wasted_cpu_core_hours: components["schemas"]["Money"];
                wasted_memory_gib_hours: components["schemas"]["Money"];
                /** @description True if any returned group was priced from a fallback guess. */
                estimated_rates: boolean;
                /**
                 * @description True when `limit` cut the results short, meaning these totals cover only the rows
                 *     returned. A partial total presented as complete is simply a wrong number.
                 */
                truncated: boolean;
            };
        };
        /** @description Only the dimension fields relevant to the requested `group_by` are present. */
        CostSummaryRow: {
            namespace?: string;
            team?: string;
            environment?: string;
            cost_centre?: string;
            workload_kind?: string;
            workload_name?: string;
            node?: string;
            instance_type?: string;
            capacity_type?: string;
            pod_name?: string;
            container_name?: string;
            cpu_requested_core_hours?: components["schemas"]["Money"];
            cpu_used_core_hours?: components["schemas"]["Money"];
            /** @description max(requested, used). This is what cost is computed from. */
            cpu_billable_core_hours?: components["schemas"]["Money"];
            memory_requested_gib_hours?: components["schemas"]["Money"];
            memory_used_gib_hours?: components["schemas"]["Money"];
            memory_billable_gib_hours?: components["schemas"]["Money"];
            /**
             * @description requested minus used, **floored at zero**. Waste cannot be negative: a container using
             *     more than it requested is under-requested, which is a reliability problem rather than a
             *     saving, and allowing it negative would offset genuine waste elsewhere in a sum.
             */
            wasted_cpu_core_hours?: components["schemas"]["Money"];
            wasted_memory_gib_hours?: components["schemas"]["Money"];
            cpu_cost?: components["schemas"]["Money"];
            memory_cost?: components["schemas"]["Money"];
            total_cost?: components["schemas"]["Money"];
            /** @description How many container-window samples were aggregated. An unexpectedly small value usually means a filter matched less than intended. */
            container_windows?: number;
            estimated_rates?: boolean;
        };
        AllocationsResponse: {
            /** Format: date-time */
            from: string;
            /** Format: date-time */
            to: string;
            count: number;
            items: components["schemas"]["AllocationRow"][];
            /**
             * @description **Absent** on the last page, so its presence answers "is there more?". An empty string
             *     would force every client to check for both absence and emptiness.
             */
            next_cursor?: string;
        };
        TrendResponse: {
            /** Format: date-time */
            from: string;
            /** Format: date-time */
            to: string;
            /** @enum {string} */
            interval: "hour" | "day" | "week" | "month";
            group_by: string;
            /**
             * @description Which table answered. PART OF THE CONTRACT, not a debug field: the two sources cannot serve
             *     the same set of questions, and the rollup only covers days the rollup job has processed. A
             *     silent choice between them is how a system becomes unexplainable.
             * @enum {string}
             */
            source: "daily_rollup" | "raw_facts";
            count: number;
            series: components["schemas"]["TrendSeries"][];
            /** @description Present only when `compare=previous_period` was requested. */
            comparison?: components["schemas"]["TrendComparison"];
        };
        TrendSeries: {
            /**
             * @description The dimension values identifying this series, keyed by column. A map rather than eleven
             *     explicit fields, because a series is IDENTIFIED by its group rather than described by it --
             *     a chart legend wants a label, not a struct with ten empty fields.
             */
            group: {
                [key: string]: string;
            };
            /** @description The sum over the returned points, so it provably matches the line beneath it. */
            total_cost: components["schemas"]["Money"];
            points: components["schemas"]["TrendPoint"][];
        };
        TrendPoint: {
            /**
             * Format: date-time
             * @description Start of the bucket, half-open to the next one.
             */
            bucket_start: string;
            total_cost: components["schemas"]["Money"];
            cpu_cost?: components["schemas"]["Money"];
            memory_cost?: components["schemas"]["Money"];
            cpu_billable_core_hours?: components["schemas"]["Money"];
            memory_billable_gib_hours?: components["schemas"]["Money"];
            wasted_cpu_core_hours?: components["schemas"]["Money"];
            wasted_memory_gib_hours?: components["schemas"]["Money"];
            /**
             * Format: int64
             * @description Samples aggregated into this bucket. **Read this alongside the cost.** A bucket with a tenth
             *     of its neighbours' window count is a collection gap, not a saving, and on a chart those two
             *     are indistinguishable.
             */
            window_count: number;
            /** @description True when any rate behind this bucket was a fallback guess. */
            estimated_rates?: boolean;
        };
        TrendComparison: {
            /** Format: date-time */
            previous_from: string;
            /** Format: date-time */
            previous_to: string;
            current_total_cost: components["schemas"]["Money"];
            previous_total_cost: components["schemas"]["Money"];
            /** @description current minus previous. Negative means it got cheaper. */
            change: components["schemas"]["Money"];
            /**
             * @description `change / previous`, as a decimal fraction. **NULL when the previous period cost nothing**,
             *     because the ratio is then undefined -- "cost went from 0 to 5" is a real and common
             *     situation (a new workload) with no percentage increase. Rendering "+Inf%" or "+100%" would
             *     state something the data does not support.
             */
            change_ratio?: string | null;
            /**
             * @description False when the two periods have materially different window counts, so part of the
             *     difference is missing data rather than changed cost. **This is the most misleading thing a
             *     trend can do:** a period during which collection started shows a large apparent increase
             *     that is purely an artefact of when the collector was deployed.
             */
            comparable: boolean;
            /** @description Why the comparison is not comparable, when it is not. */
            note?: string;
        };
        MonthlyReportsResponse: {
            items: components["schemas"]["MonthlyReport"][];
            count: number;
            /**
             * @description How many of these are not yet frozen, which tells a reader whether the page can still
             *     change. A page mixing frozen and provisional rows without saying so invites someone to
             *     quote a number that is still moving.
             */
            provisional_count: number;
            /**
             * @description The WORST coverage among the returned statements, hoisted here because it is the easiest
             *     thing on this response to overlook and the most dangerous to miss. `0.0000` on an empty
             *     page: claiming perfect coverage of nothing would read as a real measurement.
             */
            lowest_coverage: string;
        };
        MonthlyReport: {
            cluster: string;
            /**
             * @description YYYY-MM, not a timestamp. A statement is for a month, and a date would invite a reader to
             *     wonder what happened at 00:00 on the 1st.
             * @example 2026-07
             */
            month: string;
            /** @enum {string} */
            scope_kind: "cluster" | "namespace" | "team";
            scope_value: string;
            cpu_cost?: components["schemas"]["Money"];
            memory_cost?: components["schemas"]["Money"];
            total_cost: components["schemas"]["Money"];
            cpu_billable_core_hours?: components["schemas"]["Money"];
            memory_billable_gib_hours?: components["schemas"]["Money"];
            wasted_cpu_core_hours?: components["schemas"]["Money"];
            wasted_memory_gib_hours?: components["schemas"]["Money"];
            days_with_data?: number;
            days_in_month?: number;
            /** Format: int64 */
            window_count?: number;
            /**
             * @description `days_with_data / days_in_month`. **DAY-level:** a day on which the collector ran for one
             *     hour counts as a full day, so read `window_count` alongside it and use the daily trend to
             *     see a partial day as a dip. Second-level coverage would need the collection interval of
             *     every historical day, which is not recorded.
             */
            coverage: string;
            estimated_rates?: boolean;
            /** Format: date-time */
            generated_at: string;
            /**
             * Format: date-time
             * @description NULL while provisional. Once set the row is FROZEN by database trigger -- against every
             *     writer, not only the one that generates statements. This is what makes a statement
             *     quotable.
             */
            finalised_at?: string | null;
        };
        RecommendationsResponse: {
            /** Format: date-time */
            from: string;
            /** Format: date-time */
            to: string;
            count: number;
            /**
             * @description How many containers were examined. The denominator for "how much of my estate has
             *     findings" -- without it, three recommendations could mean a healthy cluster or a barely
             *     collected one.
             */
            analysed_containers: number;
            items: components["schemas"]["Recommendation"][];
            totals: {
                /** @description Sum of the POSITIVE savings only. */
                potential_monthly_saving?: components["schemas"]["Money"];
                /**
                 * @description Sum of the reliability fixes that COST money, expressed positive. Kept separate from
                 *     the savings rather than netted, so a large saving cannot hide a change someone must
                 *     make.
                 */
                required_monthly_increase?: components["schemas"]["Money"];
                critical?: number;
                warning?: number;
                info?: number;
                estimated_rates?: boolean;
            };
        };
        Recommendation: {
            /** @enum {string} */
            kind?: "right_size" | "idle" | "under_requested" | "set_requests" | "over_replicated";
            /**
             * @description Not ordered by money. `critical` is reserved for reliability risk -- a memory
             *     under-request that may cause an OOM kill -- even though fixing it increases cost.
             * @enum {string}
             */
            severity?: "info" | "warning" | "critical";
            /**
             * @description Based on observation SPAN, not sample count: a hundred windows over one hour still only
             *     describes that hour. `medium` covers a day, `high` covers a week.
             * @enum {string}
             */
            confidence?: "low" | "medium" | "high";
            namespace?: string;
            workload_kind?: string;
            workload_name?: string;
            /** @description Absent for workload-level findings such as over_replicated. */
            container_name?: string;
            summary?: string;
            /**
             * @description The reasoning, with the numbers. A recommendation nobody understands is one nobody
             *     applies -- and one that cannot be argued with cannot be trusted either.
             */
            rationale?: string;
            /** @example cpu: 500m, memory: 512Mi */
            current?: string;
            /**
             * @description Formatted in Kubernetes units so it can be pasted into a manifest unchanged.
             * @example cpu: 4m, memory: 16Mi
             */
            proposed?: string;
            /** @description NEGATIVE when the recommendation costs money, which under_requested always does. */
            estimated_monthly_saving?: components["schemas"]["Money"];
            estimated_rates?: boolean;
            /** @description The observation behind the recommendation, so it can be checked rather than believed. */
            evidence?: {
                /** Format: date-time */
                observed_from?: string;
                /** Format: date-time */
                observed_to?: string;
                observed_hours?: number;
                windows?: number;
                replicas?: number;
                cpu_requested_millicores?: number;
                /** @description The cost-relevant statistic. NOT what right-sizing uses. */
                cpu_avg_millicores?: number;
                /**
                 * @description p95 of the per-window PEAKS -- the right-sizing signal. p95 of averages would have the
                 *     bursts smoothed out of it and would understate the true peak, so a request derived
                 *     from it throttles the workload.
                 */
                cpu_p95_millicores?: number;
                cpu_max_millicores?: number;
                memory_requested_bytes?: number;
                memory_avg_bytes?: number;
                memory_p95_bytes?: number;
                memory_max_bytes?: number;
            };
        };
        AllocationRow: {
            /** Format: date-time */
            window_start?: string;
            /** Format: date-time */
            window_end?: string;
            namespace?: string;
            pod_name?: string;
            container_name?: string;
            workload_kind?: string;
            workload_name?: string;
            node_name?: string;
            team?: string;
            cost_centre?: string;
            environment?: string;
            instance_type?: string;
            /** @enum {string} */
            capacity_type?: "spot" | "on-demand";
            zone?: string;
            /** @enum {string} */
            qos_class?: "Guaranteed" | "Burstable" | "BestEffort";
            cpu_millicores_requested?: number;
            cpu_millicores_used?: number;
            cpu_millicores_billable?: number;
            memory_bytes_requested?: number;
            memory_bytes_used?: number;
            memory_bytes_billable?: number;
            cpu_cost?: components["schemas"]["Money"];
            memory_cost?: components["schemas"]["Money"];
            total_cost?: components["schemas"]["Money"];
            /**
             * @description How the rate was derived. `fallback` means the instance type was not in the catalogue and
             *     an approximate rate was used -- the figure is an estimate and must be presented as one.
             * @enum {string}
             */
            rate_source?: "catalogue" | "explicit_rates" | "fallback";
        };
        Node: {
            name?: string;
            instance_type?: string;
            region?: string;
            zone?: string;
            /** @enum {string} */
            capacity_type?: "spot" | "on-demand";
            /** @description What the instance has. **This is what you are billed for.** */
            capacity_cpu_millicores?: number;
            capacity_memory_bytes?: number;
            /** @description What the scheduler may hand out. Compute *utilisation* against this, not cost. */
            allocatable_cpu_millicores?: number;
            allocatable_memory_bytes?: number;
            ready?: boolean;
            unschedulable?: boolean;
            pricing?: {
                /** @example USD */
                currency?: string;
                node_hourly?: components["schemas"]["Money"];
                cpu_per_core_hour?: components["schemas"]["Money"];
                memory_per_gib_hour?: components["schemas"]["Money"];
                /** @enum {string} */
                source?: "catalogue" | "explicit_rates" | "fallback";
                /** @description Present when the node could not be priced. The node is still returned. */
                error?: string;
            };
        };
        HealthReport: {
            /** @enum {string} */
            status?: "up" | "down";
            checks?: {
                name?: string;
                /** @enum {string} */
                status?: "up" | "down";
                error?: string;
                latency_ms?: number;
            }[];
        };
        Error: {
            error: {
                /**
                 * @description A stable machine-readable token. Branch on this. `message` is for humans and may be
                 *     reworded at any time, so never match on it.
                 * @enum {string}
                 */
                code: "invalid_parameter" | "unauthorized" | "rate_limited" | "internal_error";
                message: string;
                /** @description Quote this when reporting a problem; it turns a vague report into a one-query log lookup. */
                request_id?: string;
                /** @description Every invalid parameter, not just the first. */
                fields?: {
                    field?: string;
                    reason?: string;
                }[];
            };
        };
    };
    responses: {
        /**
         * @description One or more parameters are invalid. Every problem is listed, so three bad parameters cost one
         *     round trip rather than three.
         */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description No valid API key. The response deliberately does not distinguish missing from wrong -- that
         *     would tell an attacker their key is the right shape.
         */
        Unauthorized: {
            headers: {
                "WWW-Authenticate"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Too many requests. Honour `Retry-After`. */
        RateLimited: {
            headers: {
                /** @description Seconds to wait. Without this a client can only guess, and most guess "immediately". */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description Something failed server-side. The response is deliberately generic; the detail is in the logs
         *     against the `request_id`, because an error body can leak SQL, hostnames and internal paths.
         */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /**
         * @description Start of the range, inclusive. RFC3339 **with a timezone**.
         *
         *     One format only, deliberately: `01/02/2026` is January 2nd or February 1st depending on
         *     where the caller lives, and guessing wrong shifts a whole cost report by a month.
         *
         *     Defaults to 24 hours before `to`.
         */
        From: string;
        /**
         * @description End of the range, **exclusive**. The range is half-open `[from, to)`, matching the collection
         *     windows -- a closed range would double-count the boundary window in two adjacent reports.
         *
         *     Defaults to now. The range may span at most 400 days.
         */
        To: string;
        Namespace: string;
        Team: string;
        Environment: string;
        CostCentre: string;
        WorkloadKind: string;
        WorkloadName: string;
        Node: string;
        InstanceType: string;
        CapacityType: "spot" | "on-demand";
        /** @description Return only rows priced from a fallback rate, to answer "how much of this bill is guessed?" */
        EstimatedOnly: boolean;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
